### ISSUE TITLE
Some more links worth to include? Perhaps, perhaps not....

### ISSUE THREAD

**Issue by Rabax55** [D-Squared70/Reading-Room#2]
a) Definitely to the book(-draft) from Justin Thaler, bc it kind of summarizes the ZKP-Realm up to today (end 2022), especially the 'Sketch' parts of some of the chapters (which give a better intuition of what ZKPs are all about "before" the badly so called "moon-math" starts - remember: there is no math on the moon; call this one guy there, he will confirm...):  
https://people.cs.georgetown.edu/jthaler/ProofsArgsAndZK.html
b) "The Mathematics behind zkSnarks" - ("legacy-Pinocchio"-based, but still good); it 'touches' a badly under-explained item: ->from general computation->signatures of the said computation -> then (zk)Proof-generation:
https://www.youtube.com/watch?v=iRQw2RpQAVc
c) To not get too intimidated to the subject, a more "musing", but  informative "Rhapsody" on zkp's (up to before PLONK came to birth, and Coda became Mina):
https://www.youtube.com/watch?v=jKSz7W5dTgY
d) Afterparty, if you're down the zk-cryptography rabbit hole: the best cryptography phd-candidates of all singers, and the best singers of all cryptography phd-candidates. Pls welcome "The Finite Simple Group":
https://www.youtube.com/watch?v=BipvGD-LCjU

**Comment by D-Squared70** [comment]
Thank you for all the recommendations, most of the above is included in the awesome lists linked in the list section. 

I'll review the content and see if anything stands and will make additions where relevant. :pray:
